In [26]:
#Debt In America Import
import pandas as pd

In [48]:
debt_data = 'Debt-in-America-Data.xlsx'

In [49]:
medical_debt = pd.read_excel(debt_data,
sheetname="Medical Debt - County",
header=0,
index_col=False,
keep_default_na=True
)

In [29]:
type(medical_debt)

pandas.core.frame.DataFrame

In [50]:
medical_debt.head()

,Unnamed: 0,Unnamed: 1,Share with debt in collections,Unnamed: 3,Unnamed: 4,Unnamed: 5,Median debt in collections,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Nonwhite population share,Unnamed: 19,Share without health insurance coverage,Unnamed: 21,Unnamed: 22,Unnamed: 23,Average household income,Unnamed: 25,Unnamed: 26
0,County,State,Overall,White areas,Nonwhite areas,NaN,Overall,White areas,Nonwhite areas,NaN,...,NaN,NaN,NaN,Overall,White,Nonwhite,NaN,Overall,White,Nonwhite
1,Autauga County,Alabama,0.34,0.33,n/a*,NaN,1336,1390,n/a*,NaN,...,NaN,0.24,NaN,0.1,0.08,0.17,NaN,64765,69780,45981
2,Baldwin County,Alabama,0.28,0.28,n/a*,NaN,1749,1745,n/a*,NaN,...,NaN,0.17,NaN,0.08,0.08,0.09,NaN,73408,75745,56869
3,Barbour County,Alabama,0.4,n/a*,n/a*,NaN,1177,n/a*,n/a*,NaN,...,NaN,0.54,NaN,0.16,0.11,0.19,NaN,44688,56667,32238
4,Bibb County,Alabama,0.47,0.45,0.57,NaN,1294,1403,n/a*,NaN,...,NaN,0.25,NaN,0.1,0.09,0.11,NaN,52241,55419,38111

In [53]:
#Need to reverse fill the merged columns
medical_debt = medical_debt.dropna(axis=1,how='all')


medical_debt.to_csv('out_ana.csv')

In [58]:
medical_debt.head()
#medical_debt_parsed = medical_debt.fillna(method='ffill', axis=1)
#medical_debt_parsed.head()

,Unnamed: 0,Unnamed: 1,Share with debt in collections,Unnamed: 3,Unnamed: 4,Median debt in collections,Unnamed: 7,Unnamed: 8,Share with medical debt in collections,Unnamed: 11,...,Median medical debt in collections,Unnamed: 15,Unnamed: 16,Nonwhite population share,Share without health insurance coverage,Unnamed: 21,Unnamed: 22,Average household income,Unnamed: 25,Unnamed: 26
0,County,State,Overall,White areas,Nonwhite areas,Overall,White areas,Nonwhite areas,Overall,White areas,...,Overall,White areas,Nonwhite areas,NaN,Overall,White,Nonwhite,Overall,White,Nonwhite
1,Autauga County,Alabama,0.34,0.33,n/a*,1336,1390,n/a*,0.11,0.11,...,413,407,n/a*,0.24,0.1,0.08,0.17,64765,69780,45981
2,Baldwin County,Alabama,0.28,0.28,n/a*,1749,1745,n/a*,0.12,0.12,...,604,628,n/a*,0.17,0.08,0.08,0.09,73408,75745,56869
3,Barbour County,Alabama,0.4,n/a*,n/a*,1177,n/a*,n/a*,0.13,n/a*,...,478,n/a*,n/a*,0.54,0.16,0.11,0.19,44688,56667,32238
4,Bibb County,Alabama,0.47,0.45,0.57,1294,1403,n/a*,0.3,0.3,...,582,637,n/a*,0.25,0.1,0.09,0.11,52241,55419,38111

In [60]:
medical_debt_renamed = medical_debt.rename(columns={'Unnamed: 0': 'County', 'Unnamed: 1': 'State',
                                                    'Unnamed: 3': 'Share with debt in collections', 'Unnamed: 4': 'Share with debt in collections',
                                                    'Unnamed: 7': 'Median debt in collections', 'Unnamed: 8': 'Median debt in collections',
                                                    'Unnamed: 11': 'Share Medical debt in collections', 'Unnamed: 12': 'Share Medical debt in collections',
                                                    'Unnamed: 15': 'Median medical debt in collections', 'Unnamed: 16': 'Median medical debt in collections', 
                                                    'Unnamed: 21': 'Share without health insurance', 'Unnamed: 22': 'Share without health insurance',
                                                    'Unnamed: 25': 'Average household income', 'Unnamed: 26': 'Average household income',
                                                   })
medical_debt_renamed.head()

,County,State,Share with debt in collections,Share with debt in collections,Share with debt in collections,Median debt in collections,Median debt in collections,Median debt in collections,Share with medical debt in collections,Share Medical debt in collections,...,Median medical debt in collections,Median medical debt in collections,Median medical debt in collections,Nonwhite population share,Share without health insurance coverage,Share without health insurance,Share without health insurance,Average household income,Average household income,Average household income
0,County,State,Overall,White areas,Nonwhite areas,Overall,White areas,Nonwhite areas,Overall,White areas,...,Overall,White areas,Nonwhite areas,NaN,Overall,White,Nonwhite,Overall,White,Nonwhite
1,Autauga County,Alabama,0.34,0.33,n/a*,1336,1390,n/a*,0.11,0.11,...,413,407,n/a*,0.24,0.1,0.08,0.17,64765,69780,45981
2,Baldwin County,Alabama,0.28,0.28,n/a*,1749,1745,n/a*,0.12,0.12,...,604,628,n/a*,0.17,0.08,0.08,0.09,73408,75745,56869
3,Barbour County,Alabama,0.4,n/a*,n/a*,1177,n/a*,n/a*,0.13,n/a*,...,478,n/a*,n/a*,0.54,0.16,0.11,0.19,44688,56667,32238
4,Bibb County,Alabama,0.47,0.45,0.57,1294,1403,n/a*,0.3,0.3,...,582,637,n/a*,0.25,0.1,0.09,0.11,52241,55419,38111

In [61]:
medical_debt_renamed.to_csv('out3.csv')